name: team_project
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^4.0.0
  http: ^0.13.5
  shared_preferences: ^2.1.0
  retry: ^3.1.0
  cupertino_icons: ^1.0.6
  table_calendar: ^3.0.3
  firebase_database: ^10.1.0
  image_picker: ^1.1.2
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true