// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIAxQUb9ygHnSN6F3tWd0VrnoXN7tL3RM',
    appId: '1:220453368114:web:59a4f90c4ce2676fa7e72b',
    messagingSenderId: '220453368114',
    projectId: 'flutter-project-c5caa',
    authDomain: 'flutter-project-c5caa.firebaseapp.com',
    databaseURL: 'https://flutter-project-c5caa-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-project-c5caa.appspot.com',
    measurementId: 'G-P2XRTD3KCR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdefOdPu-9tfJc3hZunvR4YVXD0j63eH4',
    appId: '1:220453368114:android:0107642dbe9c57c8a7e72b',
    messagingSenderId: '220453368114',
    projectId: 'flutter-project-c5caa',
    databaseURL: 'https://flutter-project-c5caa-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-project-c5caa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARaa-AY0-J-EOSkH-O1zFtiwVdhy4DnvM',
    appId: '1:220453368114:ios:401bc806f374fdcda7e72b',
    messagingSenderId: '220453368114',
    projectId: 'flutter-project-c5caa',
    databaseURL: 'https://flutter-project-c5caa-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-project-c5caa.appspot.com',
    iosBundleId: 'com.example.teamProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARaa-AY0-J-EOSkH-O1zFtiwVdhy4DnvM',
    appId: '1:220453368114:ios:401bc806f374fdcda7e72b',
    messagingSenderId: '220453368114',
    projectId: 'flutter-project-c5caa',
    databaseURL: 'https://flutter-project-c5caa-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-project-c5caa.appspot.com',
    iosBundleId: 'com.example.teamProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIAxQUb9ygHnSN6F3tWd0VrnoXN7tL3RM',
    appId: '1:220453368114:web:7e7e8222e559f093a7e72b',
    messagingSenderId: '220453368114',
    projectId: 'flutter-project-c5caa',
    authDomain: 'flutter-project-c5caa.firebaseapp.com',
    databaseURL: 'https://flutter-project-c5caa-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-project-c5caa.appspot.com',
    measurementId: 'G-K33CRFGDHN',
  );

}